name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run lint (optional)
        run: |
          # If you add ESLint, run it here. For now, this is skipped.

      - name: Run tests (optional)
        run: |
          # Add test commands here when available

      - name: Start server and test listening port
        run: |
          nohup node index.js &
          sleep 5
          curl -f http://localhost:4000/ || exit 1
